import type { Page } from '@playwright/test';
import type { Zone } from './types.js';

export const ZONE_ID_PREFIX = 'argo-overlay-';

const ZONE_POSITIONS: Record<Zone, Record<string, string>> = {
  'bottom-center': {
    position: 'fixed', bottom: '60px', left: '50%', transform: 'translateX(-50%)',
  },
  'top-left': {
    position: 'fixed', top: '40px', left: '40px',
  },
  'top-right': {
    position: 'fixed', top: '40px', right: '40px',
  },
  'bottom-left': {
    position: 'fixed', bottom: '60px', left: '40px',
  },
  'bottom-right': {
    position: 'fixed', bottom: '60px', right: '40px',
  },
  'center': {
    position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)',
  },
};

/**
 * Inject content into a zone. Replaces any existing overlay in that zone.
 * Security: contentHtml is generated by template renderers which escape all
 * text fields via escapeHtml(). Content originates from author-controlled
 * manifest files, not end-user input.
 */
export async function injectIntoZone(
  page: Page,
  zone: Zone,
  contentHtml: string,
  containerStyles: Record<string, string>,
  animationCSS?: string,
): Promise<void> {
  const zoneId = ZONE_ID_PREFIX + zone;
  const positionStyles = ZONE_POSITIONS[zone];
  const baseStyles: Record<string, string> = {
    ...positionStyles,
    zIndex: '999999',
    pointerEvents: 'none',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    ...containerStyles,
  };

  // Security note: contentHtml is generated by template renderers which escape all
  // text fields via escapeHtml(). Content originates from author-controlled manifest
  // files, not end-user input. innerHTML usage is safe in this context.
  await page.evaluate(([id, html, styles, css]) => {
    // Attach overlays to documentElement (not body) inside a Shadow DOM host
    // so they survive aggressive app re-renders that wipe body children.
    const HOST_ID = '__argo_overlay_host__';
    let host = document.getElementById(HOST_ID);
    if (!host) {
      host = document.createElement('div');
      host.id = HOST_ID;
      host.style.cssText = 'position:fixed;top:0;left:0;width:0;height:0;z-index:999999;pointer-events:none;';
      document.documentElement.appendChild(host);
      host.attachShadow({ mode: 'open' });
    }
    const shadow = host.shadowRoot!;

    const existing = shadow.getElementById(id);
    if (existing) existing.remove();

    const container = document.createElement('div');
    container.id = id;
    container.innerHTML = html; // safe — escaped by template renderers
    Object.assign(container.style, styles);

    if (css) {
      const styleEl = document.createElement('style');
      styleEl.textContent = css;
      container.appendChild(styleEl);
    }

    shadow.appendChild(container);
  }, [zoneId, contentHtml, baseStyles, animationCSS ?? ''] as const);
}

export type BackgroundTheme = 'dark' | 'light';

/**
 * Detect whether the background at a zone's position is dark or light.
 * Samples the element at the zone coordinates, skipping fixed-position elements
 * (navbars, toolbars) to read the actual page content background.
 * Returns the *overlay* theme for contrast: dark bg → 'light' overlay, light bg → 'dark' overlay.
 */
export async function detectBackgroundTheme(page: Page, zone: Zone): Promise<BackgroundTheme> {
  const pos = ZONE_POSITIONS[zone];
  return page.evaluate((zonePos) => {
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    let x = vw / 2;
    let y = vh / 2;

    if (zonePos.left === '40px') x = 80;
    else if (zonePos.right === '40px') x = vw - 80;
    else if (zonePos.left === '50%') x = vw / 2;

    if (zonePos.top === '40px') y = 80;
    else if (zonePos.bottom === '60px') y = vh - 80;
    else if (zonePos.top === '50%') y = vh / 2;

    // Get all elements at this point, skip fixed-position ones (navs, toolbars)
    const elements = document.elementsFromPoint(x, y);

    for (const el of elements) {
      const style = getComputedStyle(el);
      // Skip fixed elements (navbars, overlays) — they don't represent page content
      if (style.position === 'fixed' || style.position === 'sticky') continue;

      const bg = style.backgroundColor;
      const match = bg.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/);
      if (match) {
        const [, r, g, b, a] = match;
        const alpha = a !== undefined ? parseFloat(a) : 1;
        if (alpha > 0.1) {
          const luminance = 0.299 * Number(r) + 0.587 * Number(g) + 0.114 * Number(b);
          return luminance < 128 ? 'light' as const : 'dark' as const;
        }
      }
    }

    // Fall back: resolve CSS custom properties used for backgrounds.
    // getComputedStyle(body).backgroundColor returns transparent when
    // the background is set via CSS variables (e.g., background: var(--bg)).
    // Scan ALL custom properties on :root for background-related names,
    // not just a fixed list — catches Tailwind (--panel, --surface), shadcn,
    // and other naming conventions.
    const rootStyle = getComputedStyle(document.documentElement);

    function parseCssColor(val: string): number | null {
      const v = val.trim();
      // Hex color
      const hexMatch = v.match(/^#([0-9a-f]{3,8})$/i);
      if (hexMatch) {
        let hex = hexMatch[1];
        if (hex.length === 3) hex = hex[0]+hex[0]+hex[1]+hex[1]+hex[2]+hex[2];
        const r = parseInt(hex.slice(0, 2), 16);
        const g = parseInt(hex.slice(2, 4), 16);
        const b = parseInt(hex.slice(4, 6), 16);
        return 0.299 * r + 0.587 * g + 0.114 * b;
      }
      // rgb/rgba
      const rgbMatch = v.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
      if (rgbMatch) {
        return 0.299 * Number(rgbMatch[1]) + 0.587 * Number(rgbMatch[2]) + 0.114 * Number(rgbMatch[3]);
      }
      // oklch/hsl — convert via a hidden element
      if (/^(oklch|hsl|lch|lab)\(/.test(v)) {
        const probe = document.createElement('div');
        probe.style.cssText = 'position:absolute;width:0;height:0;background:' + v;
        document.body.appendChild(probe);
        const computed = getComputedStyle(probe).backgroundColor;
        probe.remove();
        const m = computed.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
        if (m) return 0.299 * Number(m[1]) + 0.587 * Number(m[2]) + 0.114 * Number(m[3]);
      }
      return null;
    }

    // Check well-known variable names first (fast path)
    const bgVarNames = [
      '--bg', '--background', '--bg-color', '--background-color',
      '--panel', '--surface', '--bg-primary', '--color-bg',
      '--app-bg', '--page-bg', '--body-bg',
    ];
    for (const varName of bgVarNames) {
      const varVal = rootStyle.getPropertyValue(varName).trim();
      if (!varVal) continue;
      const lum = parseCssColor(varVal);
      if (lum !== null) return lum < 128 ? 'light' as const : 'dark' as const;
    }

    // Broad scan: enumerate all custom properties on :root stylesheets
    // and check any whose name contains bg/background/surface/panel
    try {
      const bgPattern = /(?:bg|background|surface|panel|canvas|base)/i;
      for (const sheet of document.styleSheets) {
        try {
          for (const rule of sheet.cssRules) {
            if (rule instanceof CSSStyleRule && rule.selectorText === ':root') {
              for (let i = 0; i < rule.style.length; i++) {
                const prop = rule.style[i];
                if (prop.startsWith('--') && bgPattern.test(prop)) {
                  const val = rootStyle.getPropertyValue(prop).trim();
                  if (!val) continue;
                  const lum = parseCssColor(val);
                  if (lum !== null) return lum < 128 ? 'light' as const : 'dark' as const;
                }
              }
            }
          }
        } catch { /* cross-origin stylesheet — skip */ }
      }
    } catch { /* CSP or other restriction */ }

    // Check if html/body has a class indicating dark mode
    const htmlClasses = document.documentElement.className;
    const bodyClasses = document.body.className;
    if (/\bdark\b/i.test(htmlClasses) || /\bdark\b/i.test(bodyClasses)) {
      return 'light' as const;
    }

    // Last resort: system theme
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    return prefersDark ? 'light' as const : 'dark' as const;
  }, pos);
}

/**
 * Remove the overlay in the specified zone, if any.
 */
export async function removeZone(page: Page, zone: Zone): Promise<void> {
  const zoneId = ZONE_ID_PREFIX + zone;
  await page.evaluate((id) => {
    // Check shadow root first (new path), then document (legacy fallback)
    const host = document.getElementById('__argo_overlay_host__');
    const shadow = host?.shadowRoot;
    (shadow?.getElementById(id) ?? document.getElementById(id))?.remove();
    document.getElementById(id + '-style')?.remove();
  }, zoneId);
}
